package:
  name: microdrop-drc-requirements
  version: 0.1.0

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - anaconda-client
    - conda
    - conda-build
    - dmf-device-ui >=0.6
    - git
    - microdrop ==2.11
    - microdrop-launcher >=0.7.10
    - microdrop-plugin-manager >=0.24
    - pip
    - python 2.7*
    - pywget
    - pywin32
    # Install MicroDrop plugins
    - microdrop.droplet-planning-plugin
    - microdrop.dmf-device-ui-plugin
    - microdrop.dropbot-plugin >=0.10.1
    - microdrop.user-prompt-plugin
    - microdrop.step-label-plugin
    # MR-Box
    - mr-box-peripheral-board >=0.23
    - microdrop.mr-box-plugin >=0.15
    # `dropbot.py` build requirements
    - dropbot
    - paver
    - platformio-framework-arduinoteensy >=1.136.0
    - platformio-platform-teensy >=2.0.0
    - platformio-toolchain-gccarmnoneeabi

about:
  home: https://github.com/wheeler-microfluidics/microdrop-drc-requirements-recipe
  summary: MicroDrop requirements Conda meta-package for the Wheeler Lab DRC project
